### ISSUE TITLE
 ModuleNotFoundError: No module named 'Process.utils.uvr5.lib'

### ISSUE THREAD

**Issue by chen0321-max** [Spr-Aachen/Easy-Voice-Toolkit#3]
![image](https://github.com/user-attachments/assets/efa729ee-fcfc-437c-95e6-3c90c8f3cbdf)
我在co'lab上运行你的示例，报错如上，好像没有这个lib文件

**Comment by Spr-Aachen** [comment]
实在抱歉，有段时间没更新jupyter文件了，我下班以后修复一下-------- 原始邮件 --------发件人： chen0321-max ***@***.***>日期： 2024年9月4日周三 上午10:25收件人： Spr-Aachen/Easy-Voice-Toolkit ***@***.***>抄送： Subscribed ***@***.***>主    题： [Spr-Aachen/Easy-Voice-Toolkit]  ModuleNotFoundError: No module named 'Process.utils.uvr5.lib' (Issue #3)
image.png (view on web)
我在co'lab上运行你的示例，报错如上，好像没有这个lib文件

**Comment by Spr-Aachen** [comment]
简单更新了大部分内容，但还没有验证过，只能劳烦你试一下了
