### ISSUE TITLE
error in excusting wav

### ISSUE THREAD

**Issue by thefirstLeonliao** [Spr-Aachen/Easy-Voice-Toolkit#5]
TypeError: cannot unpack non-iterable NoneType object

  0%|          | 0/3 [00:00<?, ?it/s]
 33%|鈻堚枅鈻堚枎      | 1/3 [00:00<00:00,  9.98it/s]
100%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 3/3 [00:00<00:00, 10.39it/s]
100%|鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 3/3 [00:00<00:00, 10.34it/s]
Traceback (most recent call last):
  File "D:\AI\EVT_windows_x64\_internal\EVT_Core\Process\utils\Denoise_Audio.py", line 37, in uvr
    data, samplerate = pre_fun._path_audio_(
TypeError: cannot unpack non-iterable NoneType object
Finished processing.

**Comment by Spr-Aachen** [comment]
Could you please provide more details? I'm afraid I can't get enough info from this error message.

**Comment by thefirstLeonliao** [comment]
emmm就是这么个情况，我在对声音样本进行音频处理的时候，就弹出执行错误，终端里就写着这个

**Comment by Spr-Aachen** [comment]
> emmm就是这么个情况，我在对声音样本进行音频处理的时候，就弹出执行错误，终端里就写着这个

明白了，方便提供一下设置的截图吗？

**Comment by thefirstLeonliao** [comment]
> > emmm就是这么个情况，我在对声音样本进行音频处理的时候，就弹出执行错误，终端里就写着这个
> 
> 明白了谢谢，方便提供一下参数设置的截图吗？
可以的
![Uploading 微信图片_20240907004359.png…]()
![Uploading 微信图片_20240907004357.png…]()

**Comment by thefirstLeonliao** [comment]
<img width="1280" alt="微信图片_20240907004357" src="https://github.com/user-attachments/assets/46acced2-a67b-474a-9d93-953109464888">
<img width="1280" alt="微信图片_20240907004359" src="https://github.com/user-attachments/assets/796066c7-0a40-48ba-8f39-631a142024fb">

**Comment by Spr-Aachen** [comment]
输出目录里的文件是不是全的？应该是我这边异常处理没做好，在降噪时出现异常但是不影响最终输出。
